### ISSUE TITLE
Share method removed

### ISSUE THREAD

**Issue by blyleven** [sebastienheyd/hidden-captcha#1]
Hi Sebastien, 

When I tried to upgrade my Laravel application to 5.4 I noticed the following error:

###### Error
FatalThrowableError in HiddenCaptchaServiceProvider.php line 29:
Call to undefined method Illuminate\Foundation\Application::share()

###### Laravel upgrade guide
The share method has been removed from the container. This was a legacy method that has not been documented in several years. If you are using this method, you should begin using the singleton method instead:

```
$container->singleton('foo', function () {
    return 'foo';
});
```

**Comment by sebastienheyd** [comment]
Hi Michael,

Thank you for your report, this is now fixed.

**Comment by blyleven** [comment]
Hi Sebastien,

Thanks for the quick update, works great again!
